protocol=dev
host=datomic
port=4334
storage-access=remote
storage-admin-password=admin
storage-datomic-password=datomic

memory-index-threshold=32m
memory-index-max=256m
object-cache-max=128m

data-dir=/data
